language: python
python:
- '3.8'
services:
- postgresql
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c "CREATE DATABASE changesdb;" -U postgres
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: GekjeYpzjS/qXMdkh4nvh0TuDTICOKrktULwsgvkjyp6VcHyOVKYlUeAHo/FZZOMC1yv9KcshzzqI4Hkd+Sc9+kwszJ2TWoR/RX8t32NphnB5wiNqZdFXxmoLdqYTofRVyfOwrCfU3wVcS0dqJpdee545cxBgIts/oMGaN06OJ8bGblivuAjqqpAaDcdru3Gz1/STm2sm1mNAMjXobl5558YP64SLtkLSOdt/gZb26I4Sc1s8+tDiRUTtNFinrpaOxcBRw7tjQJq8UEZM3T87Pnvcj+sdMDDbQfDNEmrFrfnYAcxYoKxDRXN5dN377WZ2K/iMjTd7RXSu/G4P0FOK9wShWAsG9TsnLAX1NHDpy9WSMZ4Lm5K2xX69FYsQS2/q0fNhiAeYH+zIKkAzDvQZtoNRiW8C2VsCyO1y+itrye/8r25zIuMrumNvVWY9QbTTSUfyGCdRiIzErMEkVgXO9bjkE5H8SaCXlL3QXJyw5OwlePab3mrQeM8Dwdju4MWHQ3BA3UsAng5ORUpGoY0KAhg04gczwbkYtMwazclWh8/jNsvfUeR56/+qsRmoBJYsGOdor87ziumPBnbKktqGduzYuhs3b34TQJWQRtMq9QvA0C00+jTPNUmVSNyqpjD1LBB40Un4ZBOFLCdKdvFF9zMvOKaUAfZpm9O3Ht/yNM=
  app: fathomless-oasis-84220
  on:
    repo: uva-cs3240-s21/project-b-25
  services:
  - postgresql
